const express = require('express');
const cors = require('cors');
require('dotenv').config();
const UserRepositoryAdapter = require('./src/infrastructure/userRepositoryAdapter');
const BcryptAdapter = require('./src/infrastructure/bcryptAdapter');
const UserService = require('./src/application/userService');
const UserController = require('./src/interfaces/userController');
const app = express();
app.use(cors({origin:process.env.CORS_ORIGIN||'*',methods:['GET','POST','PUT','DELETE','OPTIONS'],allowedHeaders:['Content-Type']}));
app.use(express.json());
const userRepository=new UserRepositoryAdapter();
const passwordHasher=new BcryptAdapter();
const userService=new UserService(userRepository,passwordHasher);
const userController=new UserController(userService);
app.post('/usuarios',userController.register);
app.get('/usuarios',userController.getAll);
app.put('/usuarios/:id',userController.update);
app.delete('/usuarios/:id',userController.delete);
app.get('/',(req,res)=>res.json({mensaje:'API REST usuarios - arquitectura hexagonal',endpoints:{crear:'POST /usuarios',leer:'GET /usuarios',actualizar:'PUT /usuarios/:id',eliminar:'DELETE /usuarios/:id'}}));
const PORT=process.env.PORT||3000;
app.listen(PORT,'0.0.0.0',()=>console.log(`Backend listo en http://0.0.0.0:${PORT}`));
